#include"HTMLWriter.h"
#include<fstream>
using namespace std;

HTMLWriter::HTMLWriter()
{
	//default 파일의 이름 수정
	_fileName = "Noname.html";
	
	//default 폰트 지정
	_fontName = "돋움";
	_fontSize = 3;
	_fontColor = "black";
}

HTMLWriter::~HTMLWriter()
{
}

//파일에 텍스트 저장
void HTMLWriter::Write()
{
	//파일을 연다
	ofstream of(_fileName.c_str());

	//html 헤더 부분을 지정
	of << "<HTML><HEAD><TITLE> This document was generated by HTMLWriter</TITLE></HEAD><BODY>";
	of << "<H1>Content<H1>";

	//폰트 태그를 시작
	of << "<Font name = '" << _fontName << "' size = " << _fontSize << "' color = '" << _fontColor << "'>";

	//텍스트 저장
	of << _content;

	//폰트 태그를 닫기
	of << "</FONT>";

	//html을 마무리
	of << "</BODY></HTML>";

}

//폰트를 지정
void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor)
{
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}